apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask-app
          image: mariuslita/flask-app:v1
          ports:
          - containerPort: 5000
          env:
            - name: APP_MESSAGE
              value: "Hello from k8s!"
            - name: APP_VERSION
              value: "v1"
